### ISSUE TITLE
Saddle points not so precise

### ISSUE THREAD

**Issue by Dyson-Ido** [drhalftone/LAUCalTagWidget#3]
Hi,
  I found that the saddle points detection is not so precise as the Matlab Version. What's the difference?

**Comment by drhalftone** [comment]
Opencv

**Comment by drhalftone** [comment]
Latest version incorporates OpenCV's corner subpixel routine. That should give you better results; however, you may need to hand tune the parameters.  Right now, I have it hard coded.
